apiVersion: v1
kind: Secret
metadata:
  name: bharatclean-secrets
type: Opaque
data:
  # Base64 for 'postgresql://postgres:postgres@postgres-service:5432/bharatclean?schema=public'
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9iaGFyYXRjbGVhbj9zY2hlbWE9cHVibGlj
  # Base64 for 'some-random-secret'
  AUTH_SECRET: c29tZS1yYW5kb20tc2VjcmV0
